### ISSUE TITLE
Support Typescript v3.7 syntax

### ISSUE THREAD

**Issue by pragmasoft-ua** [theia-ide/typescript-language-server#136] opened 2020-01-06 10:03 UTC
Currently I'm getting a syntax error, when safe navigation ?. operator is used.

**Comment by martinheidegger** [comment] 2020-01-10 09:17
Noticed that this is a duplicate of #116

**Comment by apexskier** [comment] 2021-07-03 14:08
I'm not having any issue with this in https://github.com/apexskier/nova-typescript/, which uses this language server.

**Comment by rchl** [comment] 2021-07-03 18:52
Yeah, I think the original poster had an issue with either using very old `typescript` dependency in his project or not setting up `compilerOptions.target` to recent enough target.

**Closed by rchl** 2021-07-03 18:52 UTC
