### ISSUE TITLE
Error of the server

### ISSUE THREAD

**Issue by isgj** [theia-ide/typescript-language-server#163] opened 2020-11-01 10:45 UTC
Hi I'm getting this error

```shell
(node:742175) UnhandledPromiseRejectionWarning: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:399:19)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at TspClient.sendMessage (/media/data/.node_global/lib/node_modules/typescript-language-server/lib/tsp-client.js:96:33)
    at TspClient.request (/media/data/.node_global/lib/node_modules/typescript-language-server/lib/tsp-client.js:67:14)
    at LspServer.<anonymous> (/media/data/.node_global/lib/node_modules/typescript-language-server/lib/lsp-server.js:182:45)
    at Generator.next (<anonymous>)
    at /media/data/.node_global/lib/node_modules/typescript-language-server/lib/lsp-server.js:13:71
    at new Promise (<anonymous>)
    at __awaiter (/media/data/.node_global/lib/node_modules/typescript-language-server/lib/lsp-server.js:9:12)
(node:742175) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:742175) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:742175) UnhandledPromiseRejectionWarning: Error: configure timeout
    at Timeout.<anonymous> (/media/data/.node_global/lib/node_modules/typescript-language-server/lib/utils.js:24:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:742175) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)

```

Is this a problem with the server or the client is using it in the wrong way? 
Thanks

In my machine I have Node 12.19.0. The client is `lsp-mode` for emacs

**Comment by predragnikolic** [comment] 2020-11-01 10:53
Can you describe the steps to reproduce this? (Or create a minimal repo that can reproduce this bug)

**Comment by isgj** [comment] 2020-11-01 15:03
Just open any file 
```js
console.log('Hello world')
```
and try to write a second console log

**Comment by predragnikolic** [comment] 2020-11-01 22:27
I use Sublime Text with the [LSP](https://packagecontrol.io/packages/LSP) and [LSP-typescript](https://packagecontrol.io/packages/LSP-typescript) plugin and I cannot reproduce the issue you are having.

The LSP-typescript plugin uses ["typescript-language-server": "0.4.0"](https://github.com/sublimelsp/LSP-typescript/blob/9c8438d6d93425b83b78c92aadc5607483c5fd84/typescript-language-server/package.json#L6
).

My node version:
```
λ  ~  node --version
v12.18.3
```

**Comment by isgj** [comment] 2020-11-02 19:06
From the logs I see there is a permission error, but I don't know what it is trying to access 

```
Info 0    [17:27:58.865] Starting TS Server
Info 1    [17:27:58.866] Version: 4.0.5
Info 2    [17:27:58.866] Arguments: /snap/node/3168/bin/node /media/data/.node_global/bin/tsserver --logFile /home/Documents/frontend-api/.log/tsserver.log --logVerbosity info --cancellationPipeName /tmp/3b8f610ca9c4ee93deb3ff901d661adb/tscancellation*
Info 3    [17:27:58.866] Platform: linux NodeVersion: 12 CaseSensitive: true
Info 4    [17:27:58.866] ServerMode: undefined syntaxOnly: false hasUnknownServerMode: undefined
Err 5     [17:27:58.905] Exception on executing command unknown:

    EACCES: permission denied, read

    Error: EACCES: permission denied, read
Err 6     [17:27:58.945] Exception on executing command unknown:

    EACCES: permission denied, write

    Error: EACCES: permission denied, write
        at writeSync (fs.js:679:3)
        at SyncWriteStream._write (internal/fs/sync_write_stream.js:24:3)
        at doWrite (_stream_writable.js:403:12)
        at writeOrBuffer (_stream_writable.js:387:5)
        at SyncWriteStream.Writable.write (_stream_writable.js:318:11)
        at writeMessage (/media/data/.node_global/lib/node_modules/typescript/lib/tsserver.js:157436:32)
        at Object.sys.write (/media/data/.node_global/lib/node_modules/typescript/lib/tsserver.js:157539:43)
        at IOSession.Session.send (/media/data/.node_global/lib/node_modules/typescript/lib/tsserver.js:153669:27)
        at IOSession.Session.event (/media/data/.node_global/lib/node_modules/typescript/lib/tsserver.js:153672:22)
        at IOSession.event (/media/data/.node_global/lib/node_modules/typescript/lib/tsserver.js:157242:44)
        at Immediate.<anonymous> (/media/data/.node_global/lib/node_modules/typescript/lib/tsserver.js:157183:65)
        at processImmediate (internal/timers.js:461:21)
```

**Comment by predragnikolic** [comment] 2020-11-02 20:16
Looks like this issue:
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by isgj** [comment] 2020-11-03 08:20
It doesn't look to install a package there.

Is this line ok?
```
Info 4    [20:3:29.610] ServerMode: undefined syntaxOnly: false hasUnknownServerMode: undefined
```

**Comment by DonnieWest** [comment] 2020-11-03 13:20
tsserver will install types on your behalf if you're missing them for certain libraries. That aligns pretty well with the idea that this is an npm permission issue

Regardless, it's worth tackling the known exception first. Let us know once you've gotten that resolved and if you have further issues 😁

**Comment by isgj** [comment] 2020-11-03 16:43
From `ti-{somenumbers}.log` file I see
```
[17:38:35.54] Updating types-registry npm package...
[17:38:35.54] Exec: /snap/node/3168/bin/npm install --ignore-scripts types-registry@latest
[17:38:36.232]     Succeeded. stdout:
[17:38:36.232] Updated types-registry npm package
```

**Comment by isgj** [comment] 2020-12-05 16:44
If it might help now I get another error

```bash
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Socket.Writable.write (_stream_writable.js:303:10)
    at TspClient.sendMessage (/home/isgjevori/.emacs.d/.cache/lsp/npm/typescript-language-server/lib/node_modules/typescript-language-server/lib/tsp-client.js:96:33)
    at TspClient.request (/home/isgjevori/.emacs.d/.cache/lsp/npm/typescript-language-server/lib/node_modules/typescript-language-server/lib/tsp-client.js:67:14)
    at LspServer.<anonymous> (/home/isgjevori/.emacs.d/.cache/lsp/npm/typescript-language-server/lib/node_modules/typescript-language-server/lib/lsp-server.js:597:45)
    at Generator.next (<anonymous>)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

**Comment by rchl** [comment] 2021-07-03 15:36
Closing as a duplicate of #191. That other one is about the same issue and is analyzed already. The reason appears to be opening individual files rather than folders. This server doesn't support that right now.

**Closed by rchl** 2021-07-03 15:36 UTC
