### ISSUE TITLE
Rename command doesn't work on TS LS 

### ISSUE THREAD

**Issue by vrubezhny** [theia-ide/typescript-language-server#225] opened 2021-06-25 15:07 UTC
Original issue: https://github.com/eclipse/wildwebdeveloper/issues/680

On a  simple JS-file when trying to perform a rename operation (f.e., to rename a function) for some reason an undefined (null) response is received,

TS LS seems to have a problem in `textDocument/rename` handler, somewhere around https://github.com/theia-ide/typescript-language-server/blob/master/server/src/lsp-server.ts#L514 line - the array of locations returned for "rename" request is always empty.
With some extra logging enabled, the log for TS LS says:

```
[t=1624631134145] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","id":"9","method":"textDocument/rename","params":{"newName":"newNamer","textDocument":{"uri":"file:///home/user/projects/runtime-New_configuration/JsTest/test.js"},"position":{"line":0,"character":12}}}
[t=1624631134149] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"[lspserver] onRename (tspClient.request)"}}
[t=1624631134149] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"[tsclient] request {\n  \"command\": \"rename\",\n  \"seq\": 13,\n  \"type\": \"request\",\n  \"arguments\": {\n    \"file\": \"/home/user/projects/runtime-New_configuration/JsTest/test.js\",\n    \"line\": 1,\n    \"offset\": 13\n  }\n}"}}
[t=1624631134150] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"[tsclient] processMessage {\n  \"seq\": 0,\n  \"type\": \"response\",\n  \"command\": \"rename\",\n  \"request_seq\": 13,\n  \"success\": true,\n  \"body\": {\n    \"info\": {\n      \"canRename\": true,\n      \"displayName\": \"testVar\",\n      \"fullDisplayName\": \"testVar\",\n      \"kind\": \"function\",\n      \"kindModifiers\": \"\",\n      \"triggerSpan\": {\n        \"start\": {\n          \"line\": 1,\n          \"offset\": 10\n        },\n        \"end\": {\n          \"line\": 1,\n          \"offset\": 17\n        }\n      }\n    },\n    \"locs\": []\n  }\n}"}}
[t=1624631134151] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"[tsclient] request completed {\n  \"request_seq\": 13,\n  \"success\": true\n}"}}
[t=1624631134151] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"[lspserver] onRename (tspClient.request: result) {\n  \"seq\": 0,\n  \"type\": \"response\",\n  \"command\": \"rename\",\n  \"request_seq\": 13,\n  \"success\": true,\n  \"body\": {\n    \"info\": {\n      \"canRename\": true,\n      \"displayName\": \"testVar\",\n      \"fullDisplayName\": \"testVar\",\n      \"kind\": \"function\",\n      \"kindModifiers\": \"\",\n      \"triggerSpan\": {\n        \"start\": {\n          \"line\": 1,\n          \"offset\": 10\n        },\n        \"end\": {\n          \"line\": 1,\n          \"offset\": 17\n        }\n      }\n    },\n    \"locs\": []\n  }\n}"}}
[t=1624631134152] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"[lspserver] onRename (tspClient.request: result => return undefined) {\n  \"seq\": 0,\n  \"type\": \"response\",\n  \"command\": \"rename\",\n  \"request_seq\": 13,\n  \"success\": true,\n  \"body\": {\n    \"info\": {\n      \"canRename\": true,\n      \"displayName\": \"testVar\",\n      \"fullDisplayName\": \"testVar\",\n      \"kind\": \"function\",\n      \"kindModifiers\": \"\",\n      \"triggerSpan\": {\n        \"start\": {\n          \"line\": 1,\n          \"offset\": 10\n        },\n        \"end\": {\n          \"line\": 1,\n          \"offset\": 17\n        }\n      }\n    },\n    \"locs\": []\n  }\n}"}}
[t=1624631134152] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","id":"9","result":null}
```
And a simple JS-file to test renaming may look like:

```
function testVar(test) {
	if ("truetrue" == "true" + test ) {
		return true;
	}
	return false;
}

print("testVar(true) == " + testVar(true));
print("testVar(false) == " + testVar(false));
```
The log above is produced as result of trying to rename 'testVar` function after the text cursor is placed into its name in function declaration.

**Comment by danielpza** [comment] 2021-06-25 19:18
It's working for me on emacs with lsp-mode

https://user-images.githubusercontent.com/17787042/123474769-751de100-d5c8-11eb-9aa8-21209c93ed4c.mp4

**Comment by rchl** [comment] 2021-06-25 19:25
Also works for me in Sublime Text.

From the logs we can see that the LSP client sends a request to the typescript server:

```
"[tsclient] request {
  \"command\": \"rename\",
  \"seq\": 13,
  \"type\": \"request\",
  \"arguments\": {
    \"file\": \"/home/user/projects/runtime-New_configuration/JsTest/test.js\",
    \"line\": 1,
    \"offset\": 13
  }
}"
```

and that request looks correct to.

The server returns a response that doesn't include `locs` filled in:

```
"[tsclient] processMessage {
  \"seq\": 0,
  \"type\": \"response\",
  \"command\": \"rename\",
  \"request_seq\": 13,
  \"success\": true,
  \"body\": {
    \"info\": {
      \"canRename\": true,
      \"displayName\": \"testVar\",
      \"fullDisplayName\": \"testVar\",
      \"kind\": \"function\",
      \"kindModifiers\": \"\",
      \"triggerSpan\": {
        \"start\": {
          \"line\": 1,
          \"offset\": 10
        },
        \"end\": {
          \"line\": 1,
          \"offset\": 17
        }
      }
    },
    \"locs\": []
  }
}"
```

That's why it doesn't work but it doesn't look like an issue with this project. Could be something with typescript itself or how your project configures it.

You'd have to create a simple project that reproduces it if you need more help.
And if it doesn't reproduce in other editors that use this language server than you are probably on your own.

**Comment by vrubezhny** [comment] 2021-06-26 23:14
> That's why it doesn't work but it doesn't look like an issue with this project. Could be something with typescript itself or how your project configures it.
> 
Yes, I've spot the requests and responses between LSP Client and typescript server and everything looks OK except the empty locations. However in the same log I see `textDocument/documentSymbol` and `textDocument/documentHighlight` request and according  responses full of text positions pointing to the declaration/references of the same function name that I unsuccessfully tried to rename. I couldn't find any change in `rename`-related configuration options for TS LS, but probably yes it's a something to be revised. Thanks.

> You'd have to create a simple project that reproduces it if you need more help.
> And if it doesn't reproduce in other editors that use this language server than you are probably on your own.

My test project is a simple eclipse project with a single javascript file in it , not more. Document highlight, content assist, hovers - everything works but rename.

**Comment by rchl** [comment] 2021-06-27 07:03
Maybe if you would post full log from start to triggering rename then we could spot something

**Comment by vrubezhny** [comment] 2021-06-27 15:26
@rchl Please find the log attached (starting from opening the editor - through the try to get "rename" text edits - and then closing the editor): 
[org.eclipse.wildwebdeveloper.jsts.zip](https://github.com/theia-ide/typescript-language-server/files/6721810/org.eclipse.wildwebdeveloper.jsts.zip)

**Comment by rchl** [comment] 2021-06-27 21:55
After looking I still don't really know what is wrong but I've noticed that you are running with some typescript plugins:

```
                    {
                        "name": "@angular/language-service",
                        "location": "/home/user/projects/wildwebdeveloper/org.eclipse.wildwebdeveloper/node_modules/@angular/language-service"
                    },
                    {
                        "name": "typescript-plugin-css-modules",
                        "location": "/home/user/projects/wildwebdeveloper/org.eclipse.wildwebdeveloper/node_modules/typescript-plugin-css-modules"
                    },
                    {
                        "name": "typescript-lit-html-plugin",
                        "location": "/home/user/projects/wildwebdeveloper/org.eclipse.wildwebdeveloper/node_modules/typescript-lit-html-plugin"
                    }
```

so it might be worth trying without those.

And also, the typescript version from `/home/user/projects/wildwebdeveloper/org.eclipse.wildwebdeveloper/node_modules/typescript/lib/tsserver.js` is used. I'm not sure what version is that but you could try maybe using the latest version. You can force a version from different path using `--tsserver-path <path>` cli argument.

**Comment by vrubezhny** [comment] 2021-06-28 09:03
@rchl  I believe it uses tsserver v. 4.1.3

**Comment by vrubezhny** [comment] 2021-06-28 10:25
@rchl Your assumption on that running plugins could prevent 'rename' operation to work properly was right. Thanks for pointing it.

**Comment by rchl** [comment] 2021-06-28 19:21
So not a bug in this server than. Closing.

**Closed by rchl** 2021-06-28 19:21 UTC

**Comment by vrubezhny** [comment] 2021-06-29 01:46
@rchl @danielpza   Thanks for your help!
