### ISSUE TITLE
 Is it possible to support Semantic Token request

### ISSUE THREAD

**Issue by pengsongkun741** [theia-ide/typescript-language-server#183] opened 2021-01-22 09:25 UTC
A semantic token interface is defined on the Lsp protocol to obtain the semantic token information of the current document. Is it possible to support this feature, or are there other options to obtain this data. 
Looking forward to your reply, thank you！

**Comment by rchl** [comment] 2021-07-03 22:02
Duplicate of #184

**Closed by rchl** 2021-07-03 22:02 UTC
